
version:  '3.2'

services:

  server-1:
    image: "hello-world-uber-jar"
    networks:
      - docker-java
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS='-Xmx100m'

  server-2:
    image: "hello-world-uber-jar"
    networks:
      - docker-java
    ports:
      - 8081:8080
    environment:
      - JAVA_OPTS='-Xmx100m'

  server-3:
    image: "hello-world-uber-jar"
    networks:
      - docker-java
    ports:
      - 8082:8080
    environment:
      - JAVA_OPTS='-Xmx100m'

  loadbalancer:
    image: "jasonwyatt/nginx-loadbalancer"
    networks:
      - docker-java
    ports:
      - 80:80
    depends_on:
      - server-1
      - server-2
      - server-3
    env_file:
      - env.list


networks:
  docker-java: