
version:  '3.2'

services:

  server-1:
    image: "hello-world-java-war"
    networks:
      - docker-java
    ports:
      - 8080:8080
    environment:
      - JAVA_OPTS='-Xmx100m'



networks:
  docker-java: